remote_theme: pages-themes/modernist@v0.2.0
plugins_dir: jekyll-remote-theme
title: Christos Anastasiou
description: Game Engineer
show_downloads: false

# Hi there! <img src = "https://github.com/hristomanos/hristomanos/blob/main/wave.gif" width = 30 />
<p align="Justify">
My name is Christos, and I am a games programmer based in London 🇬🇧. I have two years of professional experience as a software developer at Miniclip, where I collaborated on the development and release of a mobile game titled "The Bowling Fury." As part of a talented cross-functional team, I gained hands-on experience working on various features of the game, including both front-end and back-end development.

During my undergraduate studies, I worked as a junior Unity developer during my placement year. I enjoyed discussing game mechanics with game designers and then finding solutions by designing and implementing systems for player character controls and artificial intelligence. These aspects of game development significantly influence the overall gameplay experience.

Additionally, I experimented with low-level graphics APIs such as DirectX and OpenGL, gaining insight into how technological advancements in computer graphics can dramatically enhance the visual fidelity of interactive software. However, I found low-level graphics programming less rewarding than developing game mechanics that could be quickly demonstrated during playtesting. As a result, my current aspirations are to pursue roles that focus on gameplay and AI programming.
 </p>
